### ISSUE TITLE
libmarv initialization error during GPU-accelerated search against ColabFold databases using Docker

### ISSUE THREAD

**Issue by brianloyal** [soedinglab/MMseqs2#941]
## Summary

When running GPU-accelerated search using the mmseqs2 docker image against the `colabfold_envdb_202108` or `uniref30_2302_db` databases I see an error saying

> CUDA error: initialization error : /opt/build/lib/libmarv/src/marv.cu, line 85          
> Error: Prefilter died

[That particular line](https://github.com/soedinglab/MMseqs2/blob/b804fbe384e6f6c9fe96322ec0e92d48bccd0a42/lib/libmarv/src/marv.cu#L85) is involved in getting the CUDA device count, so maybe it has something to do with seeing the GPUs on the instanc?

## Environment

- AWS g5.8xlarge EC2 instance
  - AMD EPYC 7R32 processor
  - 32x vCPU
  - 128 GiB Memory
  - 1x NVIDIA A10G accelerator (24 GiB VRAM)
- Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.5.1 (Amazon Linux 2023) 20250107
  - 6.1.119-129.201.amzn2023.x86_64 Linux distro
  - CUDA Version: 12.6
  - CUDA Driver Version: 560.35.03
  - PyTorch 2.5.1
- Container ghcr.io/soedinglab/mmseqs2:17-b804f-cuda12
  - Pulled Wednesday, January 22, 2025

## Steps to reproduce
```bash
mkdir data
wget https://www.rcsb.org/fasta/entry/1UTN -O data/1utn.fasta
wget https://wwwuser.gwdg.de/~compbiol/colabfold/colabfold_envdb_202108.tar.gz
tar -xzvf colabfold_envdb_202108.tar.gz -C data
rm colabfold_envdb_202108.tar.gz
docker pull ghcr.io/soedinglab/mmseqs2:17-b804f-cuda12
docker run -it --rm --gpus all -v "$(pwd)/data:/home/data" ghcr.io/soedinglab/mmseqs2:17-b804f-cuda12 tsv2exprofiledb "/home/data/colabfold_envdb_202108" "/home/data/targetDB" --gpu 1
docker run -it --rm --gpus all -v "$(pwd)/data:/home/data" ghcr.io/soedinglab/mmseqs2:17-b804f-cuda12 createdb "/home/data/1utn.fasta" "/home/data/queryDB"
docker run -it --rm --gpus all -v "$(pwd)/data:/home/data" ghcr.io/soedinglab/mmseqs2:17-b804f-cuda12 search "/home/data/queryDB" "/home/data/targetDB" "/home/data/result" "/home/data/tmp" --num-iterations 3 --db-load-mode 2 -a -e 0.1 --max-seqs 10000 --gpu 1 --prefilter-mode 1
```

## Things I've tried

✅ SUCCESS: Run search with `--gpu 0` (i.e. turn off GPU acceleration)
⛔ ERROR: Set the `CUDA_VISIBLE_DEVICES="0"` environment variable
⛔ ERROR: Use the `ghcr.io/soedinglab/mmseqs2:latest-cuda12` container
⛔ ERROR: Clone the GitHub repo and build the Dockerfile
⛔ ERROR: Modify the Dockerfile to COPY `/opt/build/lib/libmarv` from the build stage 
⛔ ERROR: Modify the Dockerfile to use the precompiled binary
⛔ ERROR: Run using a g5.12xlarge (4x A10G GPUs instead of 1x)

**Comment by milot-mirdita** [comment]
Does the precompiled binary work?

wget https://mmseqs.com/latest/mmseqs-linux-gpu.tar.gz

Maybe there is something wrong with the docker

**Comment by brianloyal** [comment]
@milot-mirdita Yeah, tried that too and got the same result. For my own sanity, have you been able to successfully run GPU search against the colabfold profile databases?

**Comment by milot-mirdita** [comment]
Does the following script work on the A10G instance:
```
wget https://mmseqs.com/latest/mmseqs-linux-gpu.tar.gz
tar xzvf mmseqs-linux-gpu.tar.gz
wget https://raw.githubusercontent.com/soedinglab/MMseqs2/refs/heads/master/examples/QUERY.fasta
./mmseqs/bin/mmseqs easy-search QUERY.fasta QUERY.fasta res tmp --gpu 1
```

If not,  can you try this script on an L4 or L40s based instance? We did most of our testing on those.

Is CUDA_VISIBLE_DEVICES set to some odd value?

**Comment by brianloyal** [comment]
Update: The script you shared generates the same error that I saw before, both from within the `ghcr.io/soedinglab/mmseqs2:17-b804f-cuda12` container and directly on the host

[docker_stdout.txt](https://github.com/user-attachments/files/18525879/docker_stdout.txt)

I'll try it on a L4 and L40S here in a bit and report back

**Comment by brianloyal** [comment]
Good news! The script works on both the L4 and L4S, both directly on the host and from the container. Maybe there's an issue running on Ampere?

**Comment by brianloyal** [comment]
Closing this for now, but you may want to update the [wiki](https://github.com/soedinglab/MMseqs2/wiki#compile-from-source-for-linux-with-gpu-support) to strongly encourage Lovelace-gen GPUs for best results

**Comment by milot-mirdita** [comment]
Reopening as we need to keep investigating. MMseqs2-GPU should work even on Turing (albeit rather slowly).  Ampere and newer should all work fine.

**Comment by brianloyal** [comment]
Ok, I just tried on an A100 and it also works fine, both inside and outside the container. So, at least so far, it seems specific to an A10G.

It looks like the [list of cuda architectures ](https://github.com/soedinglab/MMseqs2/blob/b804fbe384e6f6c9fe96322ec0e92d48bccd0a42/Dockerfile#L37C1-L37C90) passed to the compiler in the Docker container includes the one for A10G (8.6), so that's not the problem. Can't think of anything else that would be A10-specific, but we're just about at the edge of my depth on cuda.

**Comment by brianloyal** [comment]
One more update. I switched over to a Ubuntu AMI running CUDA 12.4 on a A10G and it worked. I've seen some [reports](https://discuss.pytorch.org/t/cuda-driver-initialization-failed-torch-cuda-is-available-false/213691) in the past of CUDA version inconsistencies when compiling on a A100 vs A10G using Amazon Linux so it's probably something to do with that. However, since (A) it works on a g5 running Ubuntu, and (B) it works on a g6 and p4 running Amazon Linux, I'm satisfied. No edits necessary to the wiki.

**Comment by achacond** [comment]
Thanks! Can you please share the Driver version used in the last run with CUDA 12.4?
If I understood correctly the issues are coming from Driver version 560.35.03 + CUDA 12.6?

**Comment by brianloyal** [comment]
Yep, that's right. The one that worked on A10G was 550.144.03 + CUDA 12.4

**Comment by agenore** [comment]
@brianloyal would you mind sharing the AMI (I didn't find it on AWS cuda 12.4) and how you started the docker ultimately?

**Comment by brianloyal** [comment]
> [@brianloyal](https://github.com/brianloyal) would you mind sharing the AMI (I didn't find it on AWS cuda 12.4) and how you started the docker ultimately?

Sure thing - this was the winner https://aws.amazon.com/releasenotes/aws-deep-learning-ami-gpu-pytorch-2-5-ubuntu-22-04/

**Comment by agenore** [comment]
thank you @brianloyal !

when deploying with that 12.4 AMI, and the docker you used ( ghcr.io/soedinglab/mmseqs2:17-b804f-cuda12 ), it returns an error that that version requires cuda 12.6

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI run
time create failed: runc create failed: unable to start container process: error during container init: erro
r running prestart hook #0: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=12.6, please update your driver to a n
ewer version, or use an earlier cuda container: unknown
```

did you just `NVIDIA_DISABLE_REQUIRE=true` and it still worked? or used other mmseqs/ami versions?

**Comment by Little-Ghost** [comment]
The same problem for me on a Nvidia H100 (535.230.02 + CUDA 12.2), when using colabfold_search.
The MMseqs2 version is a2815df9a6c6da173589fb65b3f71639ea08336d.

**Comment by milot-mirdita** [comment]
What error are you getting @Little-Ghost ? The same docker init error as the post above you? That doesn't look like an issue with MMseqs2-GPU, epecially since MMseqs2-GPU doesn't require CUDA to be installed at all, only the nvidia-driver. If you are using docker, could you try if it works without docker?

**Comment by Little-Ghost** [comment]
> What error are you getting [@Little-Ghost](https://github.com/Little-Ghost) ? The same docker init error as the post above you? That doesn't look like an issue with MMseqs2-GPU, epecially since MMseqs2-GPU doesn't require CUDA to be installed at all, only the nvidia-driver. If you are using docker, could you try if it works without docker?

I was using the [colabfold_search](https://github.com/sokrypton/ColabFold) with gpu mode. The code is like
`colabfold_search --gpu 1 batch_test.fasta ~/ColabFold/dbs msas`
or
`colabfold_search --gpu 1 --gpu-server 1 batch_test.fasta ~/ColabFold/dbs msas`
When I submitted the script to a computing node with an Nvidia H100 gpu, it gave the following error; while if with an Nvidia A100 gpu, the program ran well, and produced normal a3m results.

The complete error message is:

`Index version: 16
Generated by:  a2815df9a6c6da173589fb65b3f71639ea08336d
ScoreMatrix:  VTML80.out
CUDA error: invalid device ordinal : /home/MMseqs2/lib/libmarv/src/marv.cu, line 85
Error: Prefilter died
Traceback (most recent call last):
  File "/home/miniconda3/envs/colabfold/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/colabfold/lib/python3.9/site-packages/colabfold/mmseqs/search.py", line 450, in main
    mmseqs_search_monomer(
  File "/home/miniconda3/envs/colabfold/lib/python3.9/site-packages/colabfold/mmseqs/search.py", line 126, in mmseqs_search_monomer
    run_mmseqs(mmseqs, ["search", base.joinpath("qdb"), dbbase.joinpath(uniref_db), base.joinpath("res"), base.joinpath("tmp"), "--threads", str(threads)] + search_param)
  File "/home/miniconda3/envs/colabfold/lib/python3.9/site-packages/colabfold/mmseqs/search.py", line 45, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/home/miniconda3/envs/colabfold/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'search', PosixPath('msas/qdb'), PosixPath('/home/ColabFold/dbs/uniref30_2302_db'), PosixPath('msas/res'), PosixPath('msas/tmp'), '--threads', '64', '--num-iterations', '3', '--db-load-mode', '0', '-a', '-e', '0.1', '--max-seqs', '10000', '--gpu', '1', '--prefilter-mode', '1']' returned non-zero exit status 1.
`

**Comment by milot-mirdita** [comment]
@Little-Ghost Please make a new issue. The first issue might be because of some invalid CUDA_VISIBLE_DEVICES setting? Could you post the `nvidia-smi` output and also `echo $CUDA_VISIBLE_DEVICES`.

Regarding the second issue. What CPU does the A100 system have and how did you install/compile MMseqs2? It looks like the CPU you are using doesn't have AVX2 support, but that would imply you have a very old CPU.

Please respond in a **NEW** issue, as both these issues look to be unrelated to the rest of this issue.

**Comment by tomgoddard** [comment]
I said in the previous comment that Boltz structure prediction using CUDA on the same machine works consistently.  But I have a vague recollection that a few times it has failed and I simply reran the exact same prediction immediately after the failure and it worked.  I'll make a note if I see this happen again.  If that is right then very likely this problem is a CUDA issue not related to mmseqs.

**Comment by achacond** [comment]
Thanks for the feedback @tomgoddard 

If I understand correctly your node configuration is: Nvidia 4090, Driver Version: 575.64.03, CUDA Version: 12.9, is this correct?
Could you please make me a favor and try to reproduce the error but compiling MMseqs for your system instead the precompiled binary?

I would recommend compiling version 18 (https://github.com/soedinglab/MMseqs2/releases/tag/18-8cc5c) to match the same version that is failing to you.

Best,
Alex

**Comment by tomgoddard** [comment]
I'll try compiling MMseqs release 18 for GPU on the machine where I get the errors and see if that helps.  It may take a week because I am busy preparing a talk.

**Comment by achacond** [comment]
Hey @tomgoddard I was wondering if you had a chance to check this with more detail. Let me know if I could help you.

**Comment by tomgoddard** [comment]
I am using the standard colabfold databases uniref30_2302.tar.gz and colabfold_envdb_202108.tar.gz from

  https://colabfold.mmseqs.com

I download and make .idx files for them for efficient mmseqs GPU loading with memory mapped databases --db-load-mode 2 using the Colabfold GPU install instructions from the Colabfold github 

    https://github.com/sokrypton/ColabFold?tab=readme-ov-file#gpu-accelerated-search-with-colabfold_search

    GPU=1 ./setup_databases.sh /path/to/db_folder

Now I wonder if memory mapping the databases is connected with the crashes.  The memory map (mmap) is necessary to get good performance on single sequence searches so I always use it.  Not sure if mmseqs does memory maps the database before the libmarv cuda initialization happens.
